config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users, except: [:new]
  resources :forums
  resources :guides
  resources :activities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  get "sign_up", to: "users#new", as: :sign_up
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :comments
  belongs_to :user
  belongs_to :category

  has_rich_text :content

  validates :title, presence: true
  validates :reason, presence: true
  validates :content, presence: true
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index # Muestra recursos de una tabla
    if current_user
      @forums =
        if params[:category] && !params[:category].empty?
            Category.find_by(id: params[:category]).forums
        else
          Forum.all
        end

      if params[:q]
        @forums = @forums.filter do |forum|
          forum.title.downcase.include?(params[:q].downcase)
        end
      end
    else
      redirect_to root_path
    end
  end

  def new
    if current_user
      @forum = Forum.new
    else
      redirect_to root_path
    end
  end

  def create
    @forum = Forum.new(secure_params)
    @forum.user = current_user

    if @forum.content.empty?
        flash[:warning] = "You can't publish an empty forum"
        render :new
    else
      if @forum.save
        redirect_to @forum
      else
        flash[:warning] = "There was a problem saving, please try again and check the fields"
        render :new
      end
    end
  end

  def edit
    if current_user
      @forum = Forum.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @forum = Forum.find(params[:id])
    if params["change"] == "true"
      if @forum.solved
        @forum.solved = false
        @forum.save
        redirect_to @forum
      else
        @forum.solved = true
        @forum.save
        redirect_to @forum
      end
    else
      if @forum.update(secure_params)
        redirect_to @forum
      else
        render "edit"
      end
    end
  end

  def show
    if current_user
      @forum = Forum.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    redirect_to forums_path
  end

  private

  def secure_params
    params.require(:forum).permit(:title, :reason, :content, :category_id)
  end
end

app/views/forums/_form.html.erb
<div class="form_forum">
  <%= form_with(model: @forum, local: true) do |f| %>

    <%= render "components/input", f: f, key: :title, model: @forum %>
    <%= render "components/input", f: f, key: :reason, model: @forum %>
    <%= render "components/select", f: f, key: :category_id, options: options_for_select(Category.pluck(:name, :id)), model: @forum %>

    <%= f.label :content %>
    <%= f.rich_text_area :content%>

    <%= f.submit class: "btn_done" %>
  <% end %>
</div>

app/views/forums/edit.html.erb
<div class="form_forum_container">
    <h1>Edit Disscussion</h1>
 
    <%= render 'form' %>
    
    <%= link_to 'Back', forum_path, class: "back_to"%>
</div>

app/views/forums/index.html.erb
<div class="forums-container">
  <div class="forum-info">
      <button><a><%= link_to 'New Discussion', new_forum_path%></a></button>
      <div class="search-container">
        <%= form_with url: forums_path, method: :get, local: true do |f| %>
          <%= f.text_field :q, placeholder: "Search Discussions", type: "search" %>
          <%= f.submit "Search", class: "icon-button" %>
        <% end %>
      </div>
      <%= form_with url: forums_path, method: :get, local: true do |f| %>
        <%= f.select :category, options_for_select(Category.pluck(:name, :id), params[:category]), {prompt: "Category"}, onchange: "this.form.submit();" %>
      <% end %>
  </div>
  <div class="forum-card-container">
    <% if @forums.count.zero? %>
      <div class="empty">
        <img src="../../assets/empty_icon.png">
      </div>
    <% end %>
    <% @forums.each do |forum| %>
      <div  class="card">
        <div class="div-img">
          <%= image_tag "forum_logo.png" %>
        </div>
        <%= link_to forum.title, forum_path(forum), class: "p-title"%>
        <p class="p-date"> <%= I18n.l(forum.created_at, format: '%d %B, %Y') %></p>
        <div class="div-category">
          <p class="p-category"><%= forum.category.name %></p>
          <% if forum.solved %>
            <p class="p_status_solved">Close</p>
          <% else %>
            <p class="p_status_not_solved">Open</p>
          <% end %>


        </div>
        <p class="p-description"><%= forum.reason %></p>
        <p class="p-user"><%= forum.user.family_name %></p>
        <div class="div-comment">
          <div>
              <p><%= forum.comments.count %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/forums/new.html.erb
<div class="form_forum_container">
  <h1>New Discussion</h1>
  <%= render 'form' %>

  <%= link_to 'Back to discussions', forums_path, class: "back_to"%>
</div>

app/views/forums/show.html.erb
<div class="disscussion_container">
     <div class="show_forum">
          <div class="div_forum_header">
               <h1 class="h1_title"><%= @forum.title %></h1>
               <p class="p_date">Discussion started by <%= @forum.user.family_name %> <%= I18n.l(@forum.created_at, format: '%A, %d %B %Y') %> at <%= @forum.created_at.strftime("%H:%M") %> UTC.</p>
               <div class="div_category">
                    <p>Category: </p>
                    <p><%= @forum.category.name %><p>
               </div>
               
          </div>
          <div class="div_forum_user">
               <div class="profile_image">
                    <%= image_tag @forum.user.avatar %>
               </div>
               <div class="txt_box">
                    <p class="p_f_name"><%= @forum.user.family_name %></p>
                    <p>Comments: <%= @forum.comments.count %></p>
                    
                    <% if @forum.solved %>
                         <p>Status: Close</p>
                    <% else %>
                         <p>Status: Open</p>
                    <% end %>
               </div>
               <% if current_user == @forum.user || current_user.rank == "guild_master" %>
                    <% if @forum.solved %>
                         <%= link_to "Open", forum_path(@forum, change: true), method: :put, class: "btn_status" %>
                    <% else %>
                         <%= link_to "Close", forum_path(@forum, change: true), method: :put, class: "btn_status" %>
                    <% end %>
               <% end %>
               
               
          </div>
          <div class="div_forum_content">
               <div class="div_forum_reason">
                    <p><%= @forum.reason %></p>
                    <% if @forum.user == current_user %>
                         <%= link_to forum_path(@forum), method: :delete, data: { confirm: 'Delete Discussion?' } do %>
                              <img src="../../assets/eraser.png">
                         <%end%>
                         <%= link_to edit_forum_path(@forum) do %>
                              <img src="../../assets/feather.png">
                         <%end%>
                    <%end%>
               </div>
               <div class="content"> 
                    <%= @forum.content %>
                    <p>Last update: <%= I18n.l(@forum.updated_at, format: '%A, %d %B %Y') %> - <%= @forum.updated_at.strftime("%H:%M") %> UTC.</p>     
               </div>
               
          </div>
     </div>
     <% if @forum.solved %>
     <% else %>
          <div class="new_comment">
               <%= image_tag current_user.avatar %>
               <%= form_with(model: Comment.new , local: true) do |f| %>
                    <%= f.text_area :content, class: "textarea_write_comment", placeholder: "Write your reply" %>
                    <%= f.hidden_field :forum_id, value: @forum.id %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.submit "Post comment", class: "btn_write_comment" %>
               <% end %>
          </div>
     <% end %>
      <% if @forum.comments.count > 0 %>
          <div class="show_comments">
               <p>Comments</p>
               <% @forum.comments.each do |c| %>
                    <div class="comment_card">
                         <div class="div_user_comment_info">
                              <%= image_tag c.user.avatar %>
                              <div class="comment_info">
                                   <p class="p_comment_user_name"><%= c.user.family_name %></p>
                                   <p class="p_comment_likes">Likes: <%= c.likes.count %></p>
                                   <p class="p_comment_dislikes">Dislikes: <%= c.dislikes.count %> </p>
                              </div>
                         </div>
                         
                         <div class="comment_content">
                              <div><%= c.content %></div>
                              <p class="comment_footer"><%= c.user.family_name %>, <%= I18n.l(c.created_at, format: '%A, %d %B %Y') %> at <%= c.created_at.strftime("%H:%M") %> UTC.</p>
                              




                              <% if c != nil && %>
                                   <%= link_to comment_path(c, like: true), method: :put, class: "img_like" do %>
                                        <%= image_tag "like.png"%>
                                   <% end %>

                                   <%= link_to comment_path(c, dislike: true), method: :put, class: "img_dislike" do %>
                                        <%= image_tag "dislike.png"%>
                                   <% end %>
                              <% end %>

                              <% if c.user == current_user %>
                                <%= link_to comment_path(c), method: :delete, class: "img_delete", data: { confirm: 'Delete Comment?' } do %>
                                  <%= image_tag "eraser.png" %>
                                <%end%>
                                <%= link_to edit_comment_path(c), class: "img_feather" do %>
                                  <%= image_tag "feather.png" %>
                                <%end%>
                              <%end%>
                         </div>
                    </div>
                  <% end %>
          </div>
        <% end %>
</div>