config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users, except: [:new]
  resources :forums
  resources :guides
  resources :activities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  get "sign_up", to: "users#new", as: :sign_up
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  has_rich_text :content
  has_one_attached :avatar

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :channel, presence: true
  validates :start_time, presence: true
  validates :content, presence: true

  enum category: {pvp: 0, pve: 1, ls: 2}

  serialize :participants, Array
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :user_is_logged?
  before_action :user_is_admin?, only: [:new, :create, :edit, :destroy]

  def index # Muestra recursos de una tabla
    if current_user
      @activity_groups = Activity.where("start_time >= ?", Date.today).group_by { |a| [a.start_time.year, a.start_time.month, a.start_time.day] }
    else
      redirect_to root_path
    end
  end

  def new
    if current_user
      @activity = Activity.new
    else
      redirect_to root_path
    end
  end

  def create
    @activity = Activity.new(secure_params)
    @activity.avatar.attach(params[:activity][:avatar])
    @activity.user = current_user

    if @activity.avatar.attached?
      if @activity.save
        redirect_to @activity
      else
        render :new
      end
    else
      flash[:warning] = "You have to upload an image"
      render :new
    end
  end

  def edit
    if current_user
      @activity = Activity.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @activity = Activity.find(params[:id])

    if params["participate"] == "true"
      @activity.participants << current_user.id unless @activity.participants.include?(current_user.id)
      @activity.save

      redirect_to @activity
    else
      if @activity.avatar.attached?
        if @activity.update(secure_params)
          redirect_to @activity
        else
          render "edit"
        end
      else 
        flash[:warning] = "You have to upload an image"
        render "edit"
      end
    end

  end

  def show
    if current_user
      @activity = Activity.with_attached_avatar.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    flash[:success] = "Deleted correctly"
    redirect_to activities_path
  end

  private

  def secure_params
    params.require(:activity).permit(:title, :description, :location, :start_time, :content, :avatar, :channel, :category)
  end

  def user_is_admin?
    unless current_user.is_admin?
      flash[:danger] = "Necesitas tener el rango Guild Master o Oficial para hacer esta acción"
      redirect_to activities_path
    end
  end
end

app/views/activities/_day_card_group.html.erb
<div class="day-container">
  <div class="date">
    <p class="month"><%= Date::MONTHNAMES[day[1]] %></p>
    <p class="day"><%= day.last %></p>
  </div>

  <div class="activities">
    <% activities.each do |activity| %>
    <div class="activity" style="background-image: url('<%= url_for(activity.avatar) %>')">
      <div class="content">
        <div class="user">
          <p><%= activity.user.family_name %></p>
          <%= image_tag "dot.png" %>
          <span><%= activity.user.rank_name %></span>
        </div>

        <div class="type">
          <%= activity.category %>
        </div>

        <div class="data">
          <%= link_to activity.title, activity_path(activity) %>
          
          <p><%= activity.description %></p>
        </div>

        <div class="place">
          <%= image_tag "pin.png" %>
          
          <p><%= activity.location %></p>

          <span><%= activity.start_time.strftime("%I:%M %p") %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: @activity, local: true, ) do |f| %>
  <div class="activity-form">
    <div class="two-column">
      <div class="field">
        <%= render "components/input", f: f, key: :title, model: @activity %>
      </div>
      <div class="field">
        <%= render "components/input", f: f, key: :location, model: @activity %>
      </div>
    </div>
    <div class="two-column">
      <div class="field">
        <%= f.label :start_time %>
        <%= f.datetime_field :start_time %>
      </div>
      <div class="field">
        <%= render "components/input", f: f, key: :channel, model: @activity %>
      </div>
    </div>
    <div class="two-column">
      <div class="field">
        <%= render "components/select", f: f, key: :category, options: options_for_select(Activity.categories.to_a.map { |key, value| [key, key] }), model: @activity %>
      </div>
      <div class="field">
        <%= render "components/text", f: f, key: :description, model: @activity %> 
      </div>
    </div>
    
    <%= f.label :details %>
    <%= f.rich_text_area :content %>
    
    <div class="file">
      <label>
        <%= f.file_field :avatar %>
        Select image
      </label>
    </div>
  </div>

  <div class="actions">
    <div>
      <%= link_to 'Cancel', back_path %>

      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/activities/edit.html.erb
<div class="activity-form-container">
  <h1>Edit Activity</h1>
  
  <%= render 'form', back_path: activity_path %>
</div>

app/views/activities/index.html.erb
<div class="activities-container">
  <div class="header">
    <div>
      <h1>Activities</h1>
      <p>Don’t miss the activities that will be announced each week!</p>

      <% if current_user.is_admin? %>
        <%= link_to 'NEW', new_activity_path %>
      <% end %>
    </div>
  </div>
  
  <div class="activity-group">
    <% @activity_groups.each do |day, activities| %>
      <%= render "day_card_group.html", day: day, activities: activities %>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="activity-form-container">
  <h1>New activity</h1>

  <%= render 'form', back_path: activities_path %>
</div>

app/views/activities/show.html.erb
<div class="activity-container">
    <div class="image" style="background-image: url(<%= url_for (@activity.avatar || '')%>);"></div>

    <div class="activity">
        <div class="header">
            <h1><%= @activity.title %></h1>
            <p><%= @activity.start_time.strftime("%B %e, %Y") %></p>
            <p><%= @activity.start_time.strftime("%I:%M %p") %></p>
        </div>
        <%= @activity.content %>
        <hr class="uk-divider-icon">
        <% if @activity.user == current_user %>
            <div>
                <h1>Participants (<%= @activity.participants.count %>)</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Family name</th>
                            <th>Rank</th>
                            <th>GS</th>
                            <th>Discord</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% User.where(id: @activity.participants).each do |user| %>
                            <tr>
                                <td><%= user.family_name %></td>
                                <td><%= user.rank %></td>
                                <td><%= user.gear_score %></td>
                                <td><%= user.discord_tag %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        <% end %>

        <div class="bottom">
            <h2>Channel: <%= @activity.channel %></h2>
            <h2>Place: <%= @activity.location %></h2>

            <div class="actions">
                <% if @activity.user == current_user %>
                    <%= link_to activity_path(@activity), method: :delete, data: {confirm: "Are you sure you want to delete this activity?"} do %>
                        <%= image_tag "eraser.png" %>
                    <% end %>

                    <%= link_to edit_activity_path(@activity) do %>
                        <%= image_tag "feather.png" %>
                    <% end %>
                <% elsif !@activity.participants.include?(current_user.id) %>
                    <p>Participants <%= @activity.participants.count %></p>
                    <%= link_to "✋", activity_path(@activity, participate: true), method: :put, class: "participate" %>
                <% end %>
            </div>
        </div>
    </div>
</div>