config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users, except: [:new]
  resources :forums
  resources :guides
  resources :activities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  get "sign_up", to: "users#new", as: :sign_up
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
end

app/models/guide.rb
class Guide < ApplicationRecord
  has_many :comments
  has_rich_text :content

  belongs_to :user
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index # Muestra recursos de una tabla
    if current_user
      @guides =
      if params[:category] && params[:category] != ""
        Category.find_by(id: params[:category]).guides
      else
        Guide.all
      end

      if params[:q]
        @guides = @guides.filter do |guide|
          guide.title.downcase.include?(params[:q].downcase)
        end
      end
    else
      redirect_to root_path
    end
  end

  def new
    if current_user
      @guide = Guide.new
    else
      redirect_to root_path
    end
  end

  def create
    @guide = Guide.new(secure_params)
    @guide.user = current_user
    if @guide.content.empty?
      flash[:warning] = "You can't publish an empty guide"
      render :new
    else
      if @guide.save
        redirect_to @guide
      else
        flash[:warning] = "There was a problem saving, please try again and check the fields"
        render :new
      end
    end
  end

  def edit
    if current_user
      @guide = Guide.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @guide = Guide.find(params[:id])

    if @guide.update(secure_params)
      redirect_to @guide
    else
      flash[:warning] = "There was a problem saving, please try again and check the fields"
      render "edit"
    end
  end

  def show
    if current_user
      @guide = Guide.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy

    redirect_to guides_path
  end

  private

  def secure_params
    params.require(:guide).permit(:title, :description, :content, :category_id)
  end
end

app/views/guides/_form.html.erb
<div class="form_forum">
  <%= form_with(model: @guide, local: true) do |f| %>

    <%= render "components/input", f: f, key: :title, model: @guide %>
    <%= render "components/input", f: f, key: :description, model: @guide %>
    <%= render "components/select", f: f, key: :category_id, options: options_for_select(Category.pluck(:name, :id)), model: @guide %>

    <%= f.label :content %>
    <%= f.rich_text_area :content%>

    <%= f.submit class: "btn_done" %>
  <% end %>
</div>

app/views/guides/edit.html.erb
<div class="form_forum_container">
    <h1>Edit Guide</h1>
 
    <%= render 'form' %>
    
    <%= link_to 'Back', guide_path, class: "back_to"%>
</div>

app/views/guides/index.html.erb
<div class="forums-container">
  <div class="forum-info">
      <button><a><%= link_to 'Write Guide', new_guide_path%></a></button>
      <div class="search-container">
        <%= form_with url: guides_path, method: :get, local: true do |f| %>
          <%= f.text_field :q, placeholder: "Search Guide", type: "search" %>
          <%= f.submit "Search", class: "icon-button" %>
        <% end %>
      </div>
      <%= form_with url: guides_path, method: :get, local: true do |f| %>
        <%= f.select :category, options_for_select(Category.pluck(:name, :id), params[:category]), {prompt: "Category"}, onchange: "this.form.submit();" %>
      <% end %>
  </div>
  <div class="forum-card-container">
    <% if @guides.count.zero? %>
      <div class="empty">
        <img src="../../assets/empty_icon.png">
      </div>
    <% end %>
    <% @guides.each do |guide| %>
      <div  class="card">
        <div class="div-img">
          <%= image_tag "forum_logo.png" %>
        </div>
        <%= link_to guide.title, guide_path(guide), class: "p-title"%>
        <p class="p-date"> <%= I18n.l(guide.created_at, format: '%d %B, %Y') %></p>
        <div class="div-category">
          <p class="p-category"><%= guide.category.name %></p>
        </div>
        <p class="p-description"><%= guide.description %></p>
        <p class="p-user"><%= guide.user.family_name %></p>
        <div class="div-comment">
          <div>
              <p><%= guide.comments.count %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/guides/new.html.erb
<div class="form_forum_container">
  <h1>New Guide</h1>
  <%= render 'form' %>

  <%= link_to 'Back to guides', guides_path, class: "back_to"%>
</div>

app/views/guides/show.html.erb
<div class="disscussion_container">
     <div class="show_forum">
          <div class="div_forum_header">
               <h1 class="h1_title"><%= @guide.title %></h1>
               <p class="p_date">Guide posted by <%= @guide.user.family_name %> <%= I18n.l(@guide.created_at, format: '%A, %d %B %Y') %> at <%= @guide.created_at.strftime("%H:%M") %> UTC.</p>
               <div class="div_category">
                    <p>Category: </p>
                    <p><%= @guide.category.name %><p>
               </div>
               
          </div>
          <div class="div_forum_user">
               <div class="profile_image">
                    <%= image_tag @guide.user.avatar %>
               </div>
               <div class="txt_box">
                    <p class="p_f_name"><%= @guide.user.family_name %></p>
                    <p>Comments: <%= @guide.comments.count %></p>
               </div>
               <button class="btn_status">Close</button>
               
          </div>
          <div class="div_forum_content">
               <div class="div_forum_reason">
                    <p><%= @guide.description %></p>
                    <% if @guide.user == current_user %>
                         <%= link_to forum_path(@guide), method: :delete, data: { confirm: 'Delete Guide?' } do %>
                              <img src="../../assets/eraser.png">
                         <%end%>
                         <%= link_to edit_guide_path(@guide) do %>
                              <img src="../../assets/feather.png">
                         <%end%>
                    <%end%>
               </div>
               <div class="content"> 
                    <%= @guide.content %>
                    <p>Last update: <%= I18n.l(@guide.updated_at, format: '%A, %d %B %Y') %> - <%= @guide.updated_at.strftime("%H:%M") %> UTC.</p>     
               </div>
               
          </div>
     </div>
     <div class="new_comment">
          <%= image_tag current_user.avatar %>
          <%= form_with(model: Comment.new , local: true) do |f| %>
               <%= f.text_area :content, class: "textarea_write_comment", placeholder: "Write your reply" %>
               <%= f.hidden_field :guide_id, value: @guide.id %>
               <%= f.hidden_field :user_id, value: current_user.id %>
               <%= f.submit "Post comment", class: "btn_write_comment" %>
          <% end %>
     </div>
      <% if @guide.comments.count > 0 %>
          <div class="show_comments">
               <p>Comments </p>
               <% @guide.comments.each do |c| %>
                    <div class="comment_card">
                         <div class="div_user_comment_info">
                              <%= image_tag c.user.avatar %>
                              <div class="comment_info">
                                   <p class="p_comment_user_name"><%= c.user.family_name %></p>
                                   <p class="p_comment_likes">Likes: <%= c.likes.count %></p>
                                   <p class="p_comment_dislikes">Dislikes: <%= c.dislikes.count %> </p>
                              </div>
                         </div>
                         
                         <div class="comment_content">
                              <div><%= c.content %></div>
                              <p class="comment_footer"><%= c.user.family_name %>, <%= I18n.l(c.created_at, format: '%A, %d %B %Y') %> at <%= c.created_at.strftime("%H:%M") %> UTC.</p>
                               <% if c != nil && %>
                                   <%= link_to comment_path(c, like: true), method: :put, class: "img_like" do %>
                                        <%= image_tag "like.png"%>
                                   <% end %>

                                   <%= link_to comment_path(c, dislike: true), method: :put, class: "img_dislike" do %>
                                        <%= image_tag "dislike.png"%>
                                   <% end %>
                              <% end %>
                              <% if c.user == current_user %>
                                <%= link_to comment_path(c), method: :delete, class: "img_delete", data: { confirm: 'Delete Comment?' } do %>
                                  <%= image_tag "eraser.png" %>
                                <%end%>
                                <%= link_to edit_comment_path(c), class: "img_feather" do %>
                                  <%= image_tag "feather.png" %>
                                <%end%>
                              <%end%>
                         </div>
                    </div>
               <% end %>
          </div>
     <% end %>
</div>