config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :users, except: [:new]
  resources :forums
  resources :guides
  resources :activities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]

  get "sign_up", to: "users#new", as: :sign_up
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
end

app/views/layouts/_flashes.html.erb
<div>
  <% flash.each do |name, msg| %>
    <div class="uk-dark uk-alert-<%= name %>" uk-alert>
      <a class="uk-alert-close" uk-close style="color: black"></a>
      <p><%= msg %></p>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="media">
    <div>
      <%= link_to "https://discord.gg/GXTJjY5", target: :_blank do %>
        <%= image_tag "discord.png" %>
      <% end %>
      
      <%= link_to "https://www.blackdesertonline.com/download", class: "middle", target: :_blank do %>
        <%= image_tag "dice.png" %>
      <% end %>
      
      <%= link_to "https://www.facebook.com/Alliance-Gremory-Guild-112508870411824/", target: :_blank do %>
        <%= image_tag "facebook.png" %>
      <% end %>
    </div>
  </div>

  <div class="links">
        <p><%= link_to "About", about_path %></p>
        <p><%= link_to "Rules", root_path %></p>
        <p><%= link_to "Contact", contact_path %></p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="uk-navbar-container uk-navbar-transparent uk-background-secondary uk-padding-small" uk-navbar>
  <div class="uk-navbar-left">

    <ul class="uk-navbar-nav">
      <li class="uk-active uk-text-bold">
        <%= link_to root_path, class: "uk-logo uk-text-large", style: "font-size: 20px" do %>
          <%= image_tag "header_logo.png", class: "uk-logo" %>
           Alliance Gremory
        <% end%>
      </li>

      <% if current_user %>
        <li>
          <%= link_to "Activities", activities_path %>
        </li>
        <li>
          <%= link_to "Forums", forums_path %>
        </li>
        <li>
          <%= link_to "Guides", guides_path %>
        </li>
        <% if current_user&.is_admin? %>
          <li>
            <%= link_to "Members", users_path %>
          </li>
        <% end %>
      <% end %>

    </ul>
  </div>

  <div class="uk-navbar-right">

    <ul class="uk-navbar-nav">

      <% if current_user %>
        <li class="uk-active uk-text-bold">
          <%= link_to current_user.family_name, user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Log out", session_path(current_user.id), method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Log in", new_session_path %>
        </li>
        <li>
          <%= link_to "Sign up", sign_up_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuildManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-mutate-approach="sync"></script>

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/js/uikit-icons.min.js"></script>
  </head>

  <body style="min-height: 100vh;" class="uk-light uk-background-secondary">
    <%= render partial: "layouts/navbar" %>
    <%= render partial: "layouts/flashes" %>

    <%= yield %>

    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuildManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-mutate-approach="sync"></script>

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.4.6/dist/js/uikit-icons.min.js"></script>
  </head>

  <body style="min-height: 100vh;" class="uk-light uk-background-secondary">
    <%= yield %>
  </body>
</html>